/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jIPtables_connection_NetFilterConnTask */

#ifndef _Included_net_sf_jIPtables_connection_NetFilterConnTask
#define _Included_net_sf_jIPtables_connection_NetFilterConnTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jIPtables_connection_NetFilterConnTask
 * Method:    sendNFquery
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jIPtables_connection_NetFilterConnTask_sendNFquery
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jIPtables_connection_NetFilterConnTask
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jIPtables_connection_NetFilterConnTask_init
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jIPtables_connection_NetFilterConnTask
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jIPtables_connection_NetFilterConnTask_deinit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
