/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jIPtables_log_NetFilterLogTask */

#ifndef _Included_net_sf_jIPtables_log_NetFilterLogTask
#define _Included_net_sf_jIPtables_log_NetFilterLogTask
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_jIPtables_log_NetFilterLogTask_MIN_PRIORITY
#define net_sf_jIPtables_log_NetFilterLogTask_MIN_PRIORITY 1L
#undef net_sf_jIPtables_log_NetFilterLogTask_NORM_PRIORITY
#define net_sf_jIPtables_log_NetFilterLogTask_NORM_PRIORITY 5L
#undef net_sf_jIPtables_log_NetFilterLogTask_MAX_PRIORITY
#define net_sf_jIPtables_log_NetFilterLogTask_MAX_PRIORITY 10L
/*
 * Class:     net_sf_jIPtables_log_NetFilterLogTask
 * Method:    receiveNewPacket
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jIPtables_log_NetFilterLogTask_receiveNewPacket
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jIPtables_log_NetFilterLogTask
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_jIPtables_log_NetFilterLogTask_init
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
